// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgdqQFFJB3zpSWhn82G4Tdrd3VkQyilt4',
    appId: '1:200428539903:web:313384c7926c4047b4a1ca',
    messagingSenderId: '200428539903',
    projectId: 'chat-app-39881',
    authDomain: 'chat-app-39881.firebaseapp.com',
    storageBucket: 'chat-app-39881.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFTKEmFGiSZtZk1kBHlqeeGUzFE84KBfM',
    appId: '1:200428539903:android:22e5e898923ca66ab4a1ca',
    messagingSenderId: '200428539903',
    projectId: 'chat-app-39881',
    storageBucket: 'chat-app-39881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-xoBywPOqfaWE-TSvbhz6hXRYITDrUcw',
    appId: '1:200428539903:ios:5db5349aa1a567eeb4a1ca',
    messagingSenderId: '200428539903',
    projectId: 'chat-app-39881',
    storageBucket: 'chat-app-39881.firebasestorage.app',
    iosBundleId: 'com.example.pruebaTecnica01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-xoBywPOqfaWE-TSvbhz6hXRYITDrUcw',
    appId: '1:200428539903:ios:5db5349aa1a567eeb4a1ca',
    messagingSenderId: '200428539903',
    projectId: 'chat-app-39881',
    storageBucket: 'chat-app-39881.firebasestorage.app',
    iosBundleId: 'com.example.pruebaTecnica01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgdqQFFJB3zpSWhn82G4Tdrd3VkQyilt4',
    appId: '1:200428539903:web:c79c8d181ab7b680b4a1ca',
    messagingSenderId: '200428539903',
    projectId: 'chat-app-39881',
    authDomain: 'chat-app-39881.firebaseapp.com',
    storageBucket: 'chat-app-39881.firebasestorage.app',
  );
}
